apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: veraid-authority-queue
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: queue
          image: dev.local/veraid-authority
          args: [queue]
          env:
            - name: AUTHORITY_VERSION
              value: "1.0.0dev1"

            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password

            # Mock AWS KMS (used by WebCrypto KMS)
            - name: KMS_ADAPTER
              value: AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: aws_kms_secret_access_key
            - name: AWS_KMS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: endpoint
            - name: AWS_KMS_REGION
              value: eu-west-2
          envFrom:
            - configMapRef:
                name: mongodb
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: veraid-authority-queue-sink-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: veraid-authority-queue
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: authority-api-broker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: veraid-authority-queue-trigger
spec:
  broker: authority-api-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: veraid-authority-queue
